status = [
  "tests %",
  "canarist/%",
]

block_labels = [
  ":hand: blocked",
  ":construction: wip",
  "on hold"
]

required_approvals = 1
delete_merged_branches = true
cut_body_after = "\n\n"
timeout_sec=7200
