status = [
  "tests (10.x)",
  "tests (12.x)",
  "tests (14.x)",
  "canarist/internal-hops",
  "canarist/internal-workshop",
]

block_labels = [
  ":hand: blocked",
  ":construction: wip",
  "on hold"
]

required_approvals = 1
cut_body_after = "\n\n"
